#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "antigen"
name = "Antigen"
description.en = "Manage your ZSH plugins"
description.fr = "Gère les plugins ZSH"

version = "2.2.3~ynh4"

maintainers = ["Mistermasque"]

[upstream]
license = "MIT"
admindoc = "https://github.com/zsh-users/antigen/wiki"
code = "https://github.com/zsh-users/antigen"
fund = "https://github.com/zsh-users/antigen/issues"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "2M"
ram.build = "100M"
ram.runtime = "7M"

[install]
    [install.default_zsh]
    ask.en = "Do you want to use ZSH as default shell for all users (except root)?"
    ask.fr = "Souhaitez-vous utiliser ZSH comme shell par défaut pour tous les utilisateurs (sauf root) ?"
    type = "boolean"
    default = false

[resources]
    [resources.apt]
    packages = [
        "zsh-antigen",
    ]