#!/usr/bin/env bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

### N.B. : the following 'ynh_backup' calls are only a *declaration* of what needs
### to be backuped and not an actual copy of any file. The actual backup that
### creates and fills the archive with the files happens in the core after this
### script is called. Hence ynh_backups calls take basically 0 seconds to run.

#=================================================
# BACKUP THE CONF FILES
#=================================================

ynh_backup "$ANTIGEN_LOADER_SCRIPT"
ynh_backup "$ANTIGEN_DEFAULT_CONF"
ynh_backup "/etc/zsh/zshrc"
ynh_backup "/etc/nslcd.conf"

# TODO add saving users antigenrc files

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
