#!/usr/bin/env bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE CONF FILES
#=================================================

ynh_backup "$ANTIGEN_LOADER_SCRIPT"
ynh_backup "$ANTIGEN_DEFAULT_CONF"
ynh_backup "/etc/zsh/zshrc"
ynh_backup "/etc/yunohost/hooks.d/conf_regen/10-nslcd_${app}_app"

# TODO add saving users antigenrc files

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
