#!/usr/bin/env bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

get__root_zsh() {
    if _is_zsh_for_root_user; then
        echo "value: true"
    else
        echo "value: false"
    fi
}

#=================================================
# SPECIFIC VALIDATORS FOR TOML SHORT KEYS
#=================================================

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

# We need to create this specific setters in order to call regen-conf
# (nslcd.conf is updated with conf_regen hook)
set__default_zsh() {
    ynh_app_setting_set --app="$app" --key="default_zsh" --value="$default_zsh"
    yunohost tools regen-conf nslcd

    return 0
}

set__root_zsh() {
    if [[ "$root_zsh" == "0" ]]; then
        _unset_zsh_for_root_user
    else
        _set_zsh_for_root_user
    fi
}

#=================================================
ynh_app_config_run $1
