#!/usr/bin/env bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL ANTIGEN LOADING SCRIPT
#=================================================
ynh_script_progression "Install antigen loading scripts..."

ynh_config_add --template="load-antigen.zsh" --destination="$ANTIGEN_LOADER_SCRIPT"
chown root:root "$ANTIGEN_LOADER_SCRIPT"
chmod o+r "$ANTIGEN_LOADER_SCRIPT"

ynh_config_add --template="antigenrc" --destination="$ANTIGEN_DEFAULT_CONF"
chown root:root "$ANTIGEN_DEFAULT_CONF"
chmod o+r "$ANTIGEN_DEFAULT_CONF"

_enable_loading_antigen_by_default

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
