#!/usr/bin/env bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE ANTIGEN LOADING SCRIPT
#=================================================
ynh_script_progression --message="Remove antigen loading scripts..." --weight=1

_disable_loading_antigen_by_default
_unset_zsh_for_all_users
#_unset_zsh_for_root_user

ynh_secure_remove --file="$ANTIGEN_LOADER_SCRIPT"
ynh_secure_remove --file="$ANTIGEN_DEFAULT_CONF"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
