#!/usr/bin/env bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE ANTIGEN LOADING SCRIPT
#=================================================
ynh_script_progression "Remove antigen loading scripts..."

_disable_loading_antigen_by_default
_unset_zsh_for_all_users
#_unset_zsh_for_root_user

ynh_safe_rm "$ANTIGEN_LOADER_SCRIPT"
ynh_safe_rm "$ANTIGEN_DEFAULT_CONF"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
