#!/usr/bin/env bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE ANTIGEN LOADING SCRIPT
#=================================================

ynh_script_progression "Disable antigen loading for zsh..."
_disable_loading_antigen_by_default

ynh_script_progression "Remove antigen loading scripts..."
ynh_safe_rm "$ANTIGEN_LOADER_SCRIPT"
ynh_safe_rm "$ANTIGEN_DEFAULT_CONF"

ynh_script_progression "Remove hook script..."
ynh_safe_rm "/etc/yunohost/hooks.d/conf_regen/10-nslcd_${app}_app"

ynh_script_progression "Update nslcd configuration..."
yunohost tools regen-conf nslcd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
