#!/usr/bin/env bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Restoring config files..." --weight=1

ynh_restore_file --origin_path="$ANTIGEN_LOADER_SCRIPT"
ynh_restore_file --origin_path="$ANTIGEN_DEFAULT_CONF"
ynh_restore_file --origin_path="/etc/zsh/zshrc"
ynh_restore_file --origin_path="/etc/nslcd.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
