#!/usr/bin/env bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring config files..."

ynh_restore "$ANTIGEN_LOADER_SCRIPT"
ynh_restore "$ANTIGEN_DEFAULT_CONF"
ynh_restore "/etc/zsh/zshrc"
ynh_restore "/etc/nslcd.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
